"""initial schema

Revision ID: 08d1c2d44a65
Revises: 
Create Date: 2026-05-15 21:58:36.132131

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '08d1c2d44a65'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ablation_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('base_strategy_id', sa.Integer(), nullable=True),
    sa.Column('feature_group', sa.String(length=30), nullable=False, comment='technical|financial|news|macro|sentiment|tech_macro|tech_financial|all'),
    sa.Column('features_removed', sa.JSON(), nullable=True),
    sa.Column('sharpe', sa.Float(), nullable=True),
    sa.Column('profit_factor', sa.Float(), nullable=True),
    sa.Column('max_drawdown', sa.Float(), nullable=True),
    sa.Column('win_rate', sa.Float(), nullable=True),
    sa.Column('avg_return', sa.Float(), nullable=True),
    sa.Column('sharpe_impact', sa.Float(), nullable=True),
    sa.Column('profit_factor_impact', sa.Float(), nullable=True),
    sa.Column('drawdown_impact', sa.Float(), nullable=True),
    sa.Column('stability_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ablation_results_base_strategy_id'), 'ablation_results', ['base_strategy_id'], unique=False)
    op.create_index(op.f('ix_ablation_results_strategy_id'), 'ablation_results', ['strategy_id'], unique=False)
    op.create_table('backtest_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('backtest_run_id', sa.Integer(), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backtest_metrics_backtest_run_id'), 'backtest_metrics', ['backtest_run_id'], unique=False)
    op.create_table('backtest_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('run_type', sa.String(length=30), nullable=False),
    sa.Column('train_start', sa.Date(), nullable=False),
    sa.Column('train_end', sa.Date(), nullable=False),
    sa.Column('test_start', sa.Date(), nullable=False),
    sa.Column('test_end', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backtest_runs_strategy_id'), 'backtest_runs', ['strategy_id'], unique=False)
    op.create_table('backtest_trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('backtest_run_id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('exit_date', sa.Date(), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('exit_price', sa.Float(), nullable=False),
    sa.Column('return_pct', sa.Float(), nullable=False),
    sa.Column('pnl', sa.Float(), nullable=False),
    sa.Column('signal_strength', sa.Float(), nullable=True),
    sa.Column('exit_reason', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backtest_trades_backtest_run_id'), 'backtest_trades', ['backtest_run_id'], unique=False)
    op.create_table('corporate_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('action_date', sa.Date(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('data_source', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', 'action_date', 'action_type')
    )
    op.create_index(op.f('ix_corporate_actions_action_date'), 'corporate_actions', ['action_date'], unique=False)
    op.create_index(op.f('ix_corporate_actions_stock_id'), 'corporate_actions', ['stock_id'], unique=False)
    op.create_table('data_quality_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('week_ending', sa.Date(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('price_score', sa.Float(), nullable=False),
    sa.Column('feature_score', sa.Float(), nullable=False),
    sa.Column('financial_score', sa.Float(), nullable=False),
    sa.Column('news_score', sa.Float(), nullable=False),
    sa.Column('macro_score', sa.Float(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', 'week_ending', name='uq_dq_score_stock_week')
    )
    op.create_index(op.f('ix_data_quality_scores_stock_id'), 'data_quality_scores', ['stock_id'], unique=False)
    op.create_index(op.f('ix_data_quality_scores_week_ending'), 'data_quality_scores', ['week_ending'], unique=False)
    op.create_table('features_weekly',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('week_ending', sa.Date(), nullable=False),
    sa.Column('feature_name', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('feature_set_version', sa.String(length=50), nullable=False),
    sa.Column('computed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', 'week_ending', 'feature_name', 'feature_set_version')
    )
    op.create_index(op.f('ix_features_weekly_feature_name'), 'features_weekly', ['feature_name'], unique=False)
    op.create_index(op.f('ix_features_weekly_stock_id'), 'features_weekly', ['stock_id'], unique=False)
    op.create_index(op.f('ix_features_weekly_week_ending'), 'features_weekly', ['week_ending'], unique=False)
    op.create_table('financial_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('fiscal_period_end', sa.Date(), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=True),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('is_ttm', sa.Boolean(), nullable=False),
    sa.Column('data_source', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', 'fiscal_period_end', 'metric_name', 'as_of_date')
    )
    op.create_index(op.f('ix_financial_metrics_as_of_date'), 'financial_metrics', ['as_of_date'], unique=False)
    op.create_index(op.f('ix_financial_metrics_fiscal_period_end'), 'financial_metrics', ['fiscal_period_end'], unique=False)
    op.create_index(op.f('ix_financial_metrics_stock_id'), 'financial_metrics', ['stock_id'], unique=False)
    op.create_table('hyperparam_trials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=True),
    sa.Column('study_name', sa.String(length=200), nullable=False),
    sa.Column('trial_number', sa.Integer(), nullable=False),
    sa.Column('params_json', sa.JSON(), nullable=False),
    sa.Column('sharpe', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('study_name', 'trial_number', name='uq_hyperparam_trials_study_trial')
    )
    op.create_index(op.f('ix_hyperparam_trials_status'), 'hyperparam_trials', ['status'], unique=False)
    op.create_index(op.f('ix_hyperparam_trials_strategy_id'), 'hyperparam_trials', ['strategy_id'], unique=False)
    op.create_index(op.f('ix_hyperparam_trials_study_name'), 'hyperparam_trials', ['study_name'], unique=False)
    op.create_table('job_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('metadata', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_runs_job_name'), 'job_runs', ['job_name'], unique=False)
    op.create_table('kill_switch_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('max_paper_drawdown_weeks', sa.Integer(), nullable=False),
    sa.Column('max_paper_drawdown_pct', sa.Float(), nullable=False),
    sa.Column('max_model_drawdown_pct', sa.Float(), nullable=False),
    sa.Column('min_data_quality_score', sa.Float(), nullable=False),
    sa.Column('max_vix_level', sa.Float(), nullable=False),
    sa.Column('confidence_distribution_threshold', sa.Float(), nullable=False),
    sa.Column('min_predictions_per_week', sa.Integer(), nullable=False),
    sa.Column('max_feature_drift_pct', sa.Float(), nullable=False),
    sa.Column('enabled', sa.String(length=5), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kill_switch_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trigger_type', sa.String(length=30), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=True),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('triggered_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kill_switch_events_status'), 'kill_switch_events', ['status'], unique=False)
    op.create_index(op.f('ix_kill_switch_events_strategy_id'), 'kill_switch_events', ['strategy_id'], unique=False)
    op.create_index(op.f('ix_kill_switch_events_trigger_type'), 'kill_switch_events', ['trigger_type'], unique=False)
    op.create_table('labels_weekly',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('week_ending', sa.Date(), nullable=False),
    sa.Column('target_name', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('computed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', 'week_ending', 'target_name')
    )
    op.create_index(op.f('ix_labels_weekly_stock_id'), 'labels_weekly', ['stock_id'], unique=False)
    op.create_index(op.f('ix_labels_weekly_week_ending'), 'labels_weekly', ['week_ending'], unique=False)
    op.create_table('macro_indicators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('indicator_code', sa.String(length=50), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('indicator_code', 'date')
    )
    op.create_index(op.f('ix_macro_indicators_date'), 'macro_indicators', ['date'], unique=False)
    op.create_index(op.f('ix_macro_indicators_indicator_code'), 'macro_indicators', ['indicator_code'], unique=False)
    op.create_table('market_regimes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_starting', sa.Date(), nullable=False),
    sa.Column('week_ending', sa.Date(), nullable=False),
    sa.Column('regime_type', sa.String(length=20), nullable=False),
    sa.Column('spy_200ma_ratio', sa.Float(), nullable=True),
    sa.Column('vix_level', sa.Float(), nullable=True),
    sa.Column('vix_change', sa.Float(), nullable=True),
    sa.Column('nasdaq_spy_ratio', sa.Float(), nullable=True),
    sa.Column('market_breadth', sa.Float(), nullable=True),
    sa.Column('yield_trend', sa.Float(), nullable=True),
    sa.Column('sector_rotation_score', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_regimes_regime_type'), 'market_regimes', ['regime_type'], unique=False)
    op.create_index(op.f('ix_market_regimes_week_ending'), 'market_regimes', ['week_ending'], unique=False)
    op.create_index(op.f('ix_market_regimes_week_starting'), 'market_regimes', ['week_starting'], unique=False)
    op.create_table('meta_learner_training_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('features_json', sa.JSON(), nullable=False),
    sa.Column('label', sa.Integer(), nullable=False),
    sa.Column('paper_hit_rate', sa.Float(), nullable=True),
    sa.Column('meta_confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('strategy_id', name='uq_meta_learner_training_strategy')
    )
    op.create_index(op.f('ix_meta_learner_training_data_label'), 'meta_learner_training_data', ['label'], unique=False)
    op.create_index(op.f('ix_meta_learner_training_data_strategy_id'), 'meta_learner_training_data', ['strategy_id'], unique=False)
    op.create_table('model_promotions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('promoted_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('avg_sharpe', sa.Float(), nullable=True),
    sa.Column('deflated_sharpe', sa.Float(), nullable=True),
    sa.Column('probabilistic_sr', sa.Float(), nullable=True),
    sa.Column('permutation_pvalue', sa.Float(), nullable=True),
    sa.Column('spy_sharpe', sa.Float(), nullable=True),
    sa.Column('outperforms_spy', sa.String(length=5), nullable=True),
    sa.Column('avg_win_rate', sa.Float(), nullable=True),
    sa.Column('total_trades', sa.Integer(), nullable=True),
    sa.Column('min_drawdown', sa.Float(), nullable=True),
    sa.Column('avg_profit_factor', sa.Float(), nullable=True),
    sa.Column('concentration_ok', sa.String(length=5), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_promotions_strategy_id'), 'model_promotions', ['strategy_id'], unique=False)
    op.create_table('model_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('model_type', sa.String(length=50), nullable=False),
    sa.Column('fold', sa.Integer(), nullable=True),
    sa.Column('train_rows', sa.Integer(), nullable=True),
    sa.Column('test_rows', sa.Integer(), nullable=True),
    sa.Column('hyperparams', sa.JSON(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('feature_importance', sa.JSON(), nullable=True),
    sa.Column('model_path', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_runs_strategy_id'), 'model_runs', ['strategy_id'], unique=False)
    op.create_table('model_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('model_path', sa.String(length=500), nullable=False),
    sa.Column('feature_set_version', sa.String(length=50), nullable=True),
    sa.Column('train_start', sa.String(length=20), nullable=True),
    sa.Column('train_end', sa.String(length=20), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('holdout_period', sa.JSON(), nullable=True),
    sa.Column('validation_period', sa.JSON(), nullable=True),
    sa.Column('parent_model_id', sa.Integer(), nullable=True),
    sa.Column('promotion_reason', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('hyperparams', sa.JSON(), nullable=True),
    sa.Column('model_file_hash', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['parent_model_id'], ['model_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_versions_parent_model_id'), 'model_versions', ['parent_model_id'], unique=False)
    op.create_index(op.f('ix_model_versions_status'), 'model_versions', ['status'], unique=False)
    op.create_index(op.f('ix_model_versions_strategy_id'), 'model_versions', ['strategy_id'], unique=False)
    op.create_table('mutation_memory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feature_name', sa.String(length=100), nullable=False),
    sa.Column('mutation_type', sa.String(length=50), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('n_trials', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feature_name', 'mutation_type', name='uq_mutation_memory_feature_type')
    )
    op.create_index(op.f('ix_mutation_memory_feature_name'), 'mutation_memory', ['feature_name'], unique=False)
    op.create_index(op.f('ix_mutation_memory_mutation_type'), 'mutation_memory', ['mutation_type'], unique=False)
    op.create_table('news_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('news_id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('sentiment_label', sa.String(length=20), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('is_earnings', sa.Boolean(), nullable=False),
    sa.Column('is_legal', sa.Boolean(), nullable=False),
    sa.Column('is_product_launch', sa.Boolean(), nullable=False),
    sa.Column('is_analyst_action', sa.Boolean(), nullable=False),
    sa.Column('is_management_change', sa.Boolean(), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_analysis_news_id'), 'news_analysis', ['news_id'], unique=False)
    op.create_index(op.f('ix_news_analysis_stock_id'), 'news_analysis', ['stock_id'], unique=False)
    op.create_table('news_articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url_hash', sa.String(length=64), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('headline', sa.String(length=500), nullable=True),
    sa.Column('body_excerpt', sa.Text(), nullable=True),
    sa.Column('ticker_mentions', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_articles_published_at'), 'news_articles', ['published_at'], unique=False)
    op.create_index(op.f('ix_news_articles_url_hash'), 'news_articles', ['url_hash'], unique=True)
    op.create_table('paper_trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prediction_id', sa.Integer(), nullable=False),
    sa.Column('week_starting', sa.Date(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('prob_2pct', sa.Float(), nullable=True),
    sa.Column('prob_loss_2pct', sa.Float(), nullable=True),
    sa.Column('expected_return', sa.Float(), nullable=True),
    sa.Column('confidence', sa.String(length=20), nullable=True),
    sa.Column('signal_summary', sa.String(length=500), nullable=True),
    sa.Column('entry_date', sa.Date(), nullable=True),
    sa.Column('planned_exit_date', sa.Date(), nullable=False),
    sa.Column('exit_date', sa.Date(), nullable=True),
    sa.Column('entry_price', sa.Float(), nullable=True),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('realized_return', sa.Float(), nullable=True),
    sa.Column('max_rise_in_period', sa.Float(), nullable=True),
    sa.Column('max_drawdown_in_period', sa.Float(), nullable=True),
    sa.Column('hit_2pct', sa.Boolean(), nullable=True),
    sa.Column('hit_3pct', sa.Boolean(), nullable=True),
    sa.Column('hit_loss_2pct', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prediction_id', name='uq_paper_trades_prediction')
    )
    op.create_index(op.f('ix_paper_trades_prediction_id'), 'paper_trades', ['prediction_id'], unique=False)
    op.create_index(op.f('ix_paper_trades_status'), 'paper_trades', ['status'], unique=False)
    op.create_index(op.f('ix_paper_trades_stock_id'), 'paper_trades', ['stock_id'], unique=False)
    op.create_index(op.f('ix_paper_trades_strategy_id'), 'paper_trades', ['strategy_id'], unique=False)
    op.create_index(op.f('ix_paper_trades_week_starting'), 'paper_trades', ['week_starting'], unique=False)
    op.create_table('pead_signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('earnings_date', sa.Date(), nullable=False),
    sa.Column('actual_eps', sa.Float(), nullable=True),
    sa.Column('expected_eps', sa.Float(), nullable=True),
    sa.Column('sue_score', sa.Float(), nullable=True),
    sa.Column('earnings_day_return', sa.Float(), nullable=True),
    sa.Column('post_earnings_week1', sa.Float(), nullable=True),
    sa.Column('earnings_volume_ratio', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', 'earnings_date', name='uq_pead_signals_stock_date')
    )
    op.create_index(op.f('ix_pead_signals_stock_id'), 'pead_signals', ['stock_id'], unique=False)
    op.create_table('prices_daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('adj_close', sa.Float(), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('data_source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', 'date')
    )
    op.create_index(op.f('ix_prices_daily_date'), 'prices_daily', ['date'], unique=False)
    op.create_index(op.f('ix_prices_daily_stock_id'), 'prices_daily', ['stock_id'], unique=False)
    op.create_table('prices_weekly',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('week_ending', sa.Date(), nullable=False),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('weekly_return', sa.Float(), nullable=True),
    sa.Column('realized_volatility', sa.Float(), nullable=True),
    sa.Column('max_drawdown_in_week', sa.Float(), nullable=True),
    sa.Column('max_rise_in_week', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', 'week_ending')
    )
    op.create_index(op.f('ix_prices_weekly_stock_id'), 'prices_weekly', ['stock_id'], unique=False)
    op.create_index(op.f('ix_prices_weekly_week_ending'), 'prices_weekly', ['week_ending'], unique=False)
    op.create_table('probability_calibrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('week_starting', sa.Date(), nullable=False),
    sa.Column('brier_score', sa.Float(), nullable=True),
    sa.Column('calibration_error', sa.Float(), nullable=True),
    sa.Column('prob_buckets', sa.JSON(), nullable=True),
    sa.Column('reliability_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_probability_calibrations_strategy_id'), 'probability_calibrations', ['strategy_id'], unique=False)
    op.create_index(op.f('ix_probability_calibrations_week_starting'), 'probability_calibrations', ['week_starting'], unique=False)
    op.create_table('research_trial_budgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('budget_date', sa.Date(), nullable=False),
    sa.Column('iterations_used', sa.Integer(), nullable=False),
    sa.Column('max_iterations', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('budget_date', name='uq_research_trial_budgets_date')
    )
    op.create_index(op.f('ix_research_trial_budgets_budget_date'), 'research_trial_budgets', ['budget_date'], unique=False)
    op.create_table('rl_agent_qtable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('qtable_json', sa.JSON(), nullable=False),
    sa.Column('epsilon', sa.Float(), nullable=False),
    sa.Column('steps', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_name', name='uq_rl_agent_qtable_agent')
    )
    op.create_index(op.f('ix_rl_agent_qtable_agent_name'), 'rl_agent_qtable', ['agent_name'], unique=False)
    op.create_table('selected_stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_starting', sa.String(length=20), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('signal', sa.String(length=30), nullable=True),
    sa.Column('confidence', sa.String(length=20), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_selected_stocks_week_starting'), 'selected_stocks', ['week_starting'], unique=False)
    op.create_table('short_interest_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('short_shares', sa.Float(), nullable=True),
    sa.Column('float_shares', sa.Float(), nullable=True),
    sa.Column('short_ratio', sa.Float(), nullable=True),
    sa.Column('short_pct_float', sa.Float(), nullable=True),
    sa.Column('avg_daily_volume', sa.Float(), nullable=True),
    sa.Column('short_volume_ratio', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', 'report_date', name='uq_short_interest_stock_date')
    )
    op.create_index(op.f('ix_short_interest_data_stock_id'), 'short_interest_data', ['stock_id'], unique=False)
    op.create_table('social_sentiment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('week_ending', sa.String(length=20), nullable=False),
    sa.Column('mention_count', sa.Integer(), nullable=True),
    sa.Column('mention_momentum', sa.Float(), nullable=True),
    sa.Column('sentiment_polarity', sa.Float(), nullable=True),
    sa.Column('hype_risk', sa.Float(), nullable=True),
    sa.Column('abnormal_attention', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', 'week_ending', 'source', name='uq_social_stock_week_source')
    )
    op.create_index(op.f('ix_social_sentiment_stock_id'), 'social_sentiment', ['stock_id'], unique=False)
    op.create_index(op.f('ix_social_sentiment_week_ending'), 'social_sentiment', ['week_ending'], unique=False)
    op.create_table('stock_universe_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('index_name', sa.String(length=50), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_date', 'index_name', 'ticker')
    )
    op.create_index(op.f('ix_stock_universe_snapshots_snapshot_date'), 'stock_universe_snapshots', ['snapshot_date'], unique=False)
    op.create_index(op.f('ix_stock_universe_snapshots_ticker'), 'stock_universe_snapshots', ['ticker'], unique=False)
    op.create_table('stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('exchange', sa.String(length=20), nullable=True),
    sa.Column('ipo_date', sa.Date(), nullable=True),
    sa.Column('delisting_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stocks_ticker'), 'stocks', ['ticker'], unique=True)
    op.create_table('strategies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('parent_strategy_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('promoted_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategies_status'), 'strategies', ['status'], unique=False)
    op.create_table('strategy_bandit_arms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('alpha', sa.Integer(), nullable=False),
    sa.Column('beta', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('strategy_id', name='uq_strategy_bandit_arms_strategy')
    )
    op.create_index(op.f('ix_strategy_bandit_arms_strategy_id'), 'strategy_bandit_arms', ['strategy_id'], unique=False)
    op.create_table('strategy_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('rule_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('feature_name', sa.String(length=100), nullable=True),
    sa.Column('operator', sa.String(length=10), nullable=True),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('importance', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategy_rules_strategy_id'), 'strategy_rules', ['strategy_id'], unique=False)
    op.create_table('ticker_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('old_ticker', sa.String(length=20), nullable=False),
    sa.Column('new_ticker', sa.String(length=20), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('old_ticker', 'new_ticker', 'effective_date')
    )
    op.create_index(op.f('ix_ticker_aliases_effective_date'), 'ticker_aliases', ['effective_date'], unique=False)
    op.create_index(op.f('ix_ticker_aliases_new_ticker'), 'ticker_aliases', ['new_ticker'], unique=False)
    op.create_index(op.f('ix_ticker_aliases_old_ticker'), 'ticker_aliases', ['old_ticker'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('walk_forward_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('fold', sa.Integer(), nullable=False),
    sa.Column('train_start', sa.Date(), nullable=False),
    sa.Column('train_end', sa.Date(), nullable=False),
    sa.Column('test_start', sa.Date(), nullable=False),
    sa.Column('test_end', sa.Date(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('equity_curve', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_walk_forward_results_strategy_id'), 'walk_forward_results', ['strategy_id'], unique=False)
    op.create_table('weekly_predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_starting', sa.Date(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('prob_2pct', sa.Float(), nullable=True),
    sa.Column('prob_loss_2pct', sa.Float(), nullable=True),
    sa.Column('expected_return', sa.Float(), nullable=True),
    sa.Column('confidence', sa.String(length=20), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('signal_summary', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('week_starting', 'stock_id', 'strategy_id', name='uq_weekly_predictions_week_stock_strategy')
    )
    op.create_index(op.f('ix_weekly_predictions_stock_id'), 'weekly_predictions', ['stock_id'], unique=False)
    op.create_index(op.f('ix_weekly_predictions_week_starting'), 'weekly_predictions', ['week_starting'], unique=False)
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(length=100), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=False)
    op.create_index(op.f('ix_api_keys_user_id'), 'api_keys', ['user_id'], unique=False)
    op.create_table('portfolio_simulations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('backtest_run_id', sa.Integer(), nullable=True),
    sa.Column('initial_capital', sa.Float(), nullable=False),
    sa.Column('max_positions', sa.Integer(), nullable=False),
    sa.Column('max_position_weight', sa.Float(), nullable=False),
    sa.Column('sector_limit', sa.Float(), nullable=False),
    sa.Column('cash_ratio', sa.Float(), nullable=False),
    sa.Column('rebalance_frequency', sa.String(length=20), nullable=False),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('take_profit', sa.Float(), nullable=True),
    sa.Column('transaction_cost_bps', sa.Float(), nullable=False),
    sa.Column('slippage_bps', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['backtest_run_id'], ['backtest_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_simulations_backtest_run_id'), 'portfolio_simulations', ['backtest_run_id'], unique=False)
    op.create_index(op.f('ix_portfolio_simulations_strategy_id'), 'portfolio_simulations', ['strategy_id'], unique=False)
    op.create_table('portfolio_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('simulation_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_value', sa.Float(), nullable=False),
    sa.Column('cash_value', sa.Float(), nullable=False),
    sa.Column('invested_value', sa.Float(), nullable=False),
    sa.Column('n_positions', sa.Integer(), nullable=False),
    sa.Column('sector_exposure', sa.JSON(), nullable=False),
    sa.Column('monthly_return', sa.Float(), nullable=True),
    sa.Column('ytd_return', sa.Float(), nullable=True),
    sa.Column('drawdown', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['simulation_id'], ['portfolio_simulations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_snapshots_date'), 'portfolio_snapshots', ['date'], unique=False)
    op.create_index(op.f('ix_portfolio_snapshots_simulation_id'), 'portfolio_snapshots', ['simulation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_portfolio_snapshots_simulation_id'), table_name='portfolio_snapshots')
    op.drop_index(op.f('ix_portfolio_snapshots_date'), table_name='portfolio_snapshots')
    op.drop_table('portfolio_snapshots')
    op.drop_index(op.f('ix_portfolio_simulations_strategy_id'), table_name='portfolio_simulations')
    op.drop_index(op.f('ix_portfolio_simulations_backtest_run_id'), table_name='portfolio_simulations')
    op.drop_table('portfolio_simulations')
    op.drop_index(op.f('ix_api_keys_user_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_weekly_predictions_week_starting'), table_name='weekly_predictions')
    op.drop_index(op.f('ix_weekly_predictions_stock_id'), table_name='weekly_predictions')
    op.drop_table('weekly_predictions')
    op.drop_index(op.f('ix_walk_forward_results_strategy_id'), table_name='walk_forward_results')
    op.drop_table('walk_forward_results')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_ticker_aliases_old_ticker'), table_name='ticker_aliases')
    op.drop_index(op.f('ix_ticker_aliases_new_ticker'), table_name='ticker_aliases')
    op.drop_index(op.f('ix_ticker_aliases_effective_date'), table_name='ticker_aliases')
    op.drop_table('ticker_aliases')
    op.drop_index(op.f('ix_strategy_rules_strategy_id'), table_name='strategy_rules')
    op.drop_table('strategy_rules')
    op.drop_index(op.f('ix_strategy_bandit_arms_strategy_id'), table_name='strategy_bandit_arms')
    op.drop_table('strategy_bandit_arms')
    op.drop_index(op.f('ix_strategies_status'), table_name='strategies')
    op.drop_table('strategies')
    op.drop_index(op.f('ix_stocks_ticker'), table_name='stocks')
    op.drop_table('stocks')
    op.drop_index(op.f('ix_stock_universe_snapshots_ticker'), table_name='stock_universe_snapshots')
    op.drop_index(op.f('ix_stock_universe_snapshots_snapshot_date'), table_name='stock_universe_snapshots')
    op.drop_table('stock_universe_snapshots')
    op.drop_index(op.f('ix_social_sentiment_week_ending'), table_name='social_sentiment')
    op.drop_index(op.f('ix_social_sentiment_stock_id'), table_name='social_sentiment')
    op.drop_table('social_sentiment')
    op.drop_index(op.f('ix_short_interest_data_stock_id'), table_name='short_interest_data')
    op.drop_table('short_interest_data')
    op.drop_index(op.f('ix_selected_stocks_week_starting'), table_name='selected_stocks')
    op.drop_table('selected_stocks')
    op.drop_index(op.f('ix_rl_agent_qtable_agent_name'), table_name='rl_agent_qtable')
    op.drop_table('rl_agent_qtable')
    op.drop_index(op.f('ix_research_trial_budgets_budget_date'), table_name='research_trial_budgets')
    op.drop_table('research_trial_budgets')
    op.drop_index(op.f('ix_probability_calibrations_week_starting'), table_name='probability_calibrations')
    op.drop_index(op.f('ix_probability_calibrations_strategy_id'), table_name='probability_calibrations')
    op.drop_table('probability_calibrations')
    op.drop_index(op.f('ix_prices_weekly_week_ending'), table_name='prices_weekly')
    op.drop_index(op.f('ix_prices_weekly_stock_id'), table_name='prices_weekly')
    op.drop_table('prices_weekly')
    op.drop_index(op.f('ix_prices_daily_stock_id'), table_name='prices_daily')
    op.drop_index(op.f('ix_prices_daily_date'), table_name='prices_daily')
    op.drop_table('prices_daily')
    op.drop_index(op.f('ix_pead_signals_stock_id'), table_name='pead_signals')
    op.drop_table('pead_signals')
    op.drop_index(op.f('ix_paper_trades_week_starting'), table_name='paper_trades')
    op.drop_index(op.f('ix_paper_trades_strategy_id'), table_name='paper_trades')
    op.drop_index(op.f('ix_paper_trades_stock_id'), table_name='paper_trades')
    op.drop_index(op.f('ix_paper_trades_status'), table_name='paper_trades')
    op.drop_index(op.f('ix_paper_trades_prediction_id'), table_name='paper_trades')
    op.drop_table('paper_trades')
    op.drop_index(op.f('ix_news_articles_url_hash'), table_name='news_articles')
    op.drop_index(op.f('ix_news_articles_published_at'), table_name='news_articles')
    op.drop_table('news_articles')
    op.drop_index(op.f('ix_news_analysis_stock_id'), table_name='news_analysis')
    op.drop_index(op.f('ix_news_analysis_news_id'), table_name='news_analysis')
    op.drop_table('news_analysis')
    op.drop_index(op.f('ix_mutation_memory_mutation_type'), table_name='mutation_memory')
    op.drop_index(op.f('ix_mutation_memory_feature_name'), table_name='mutation_memory')
    op.drop_table('mutation_memory')
    op.drop_index(op.f('ix_model_versions_strategy_id'), table_name='model_versions')
    op.drop_index(op.f('ix_model_versions_status'), table_name='model_versions')
    op.drop_index(op.f('ix_model_versions_parent_model_id'), table_name='model_versions')
    op.drop_table('model_versions')
    op.drop_index(op.f('ix_model_runs_strategy_id'), table_name='model_runs')
    op.drop_table('model_runs')
    op.drop_index(op.f('ix_model_promotions_strategy_id'), table_name='model_promotions')
    op.drop_table('model_promotions')
    op.drop_index(op.f('ix_meta_learner_training_data_strategy_id'), table_name='meta_learner_training_data')
    op.drop_index(op.f('ix_meta_learner_training_data_label'), table_name='meta_learner_training_data')
    op.drop_table('meta_learner_training_data')
    op.drop_index(op.f('ix_market_regimes_week_starting'), table_name='market_regimes')
    op.drop_index(op.f('ix_market_regimes_week_ending'), table_name='market_regimes')
    op.drop_index(op.f('ix_market_regimes_regime_type'), table_name='market_regimes')
    op.drop_table('market_regimes')
    op.drop_index(op.f('ix_macro_indicators_indicator_code'), table_name='macro_indicators')
    op.drop_index(op.f('ix_macro_indicators_date'), table_name='macro_indicators')
    op.drop_table('macro_indicators')
    op.drop_index(op.f('ix_labels_weekly_week_ending'), table_name='labels_weekly')
    op.drop_index(op.f('ix_labels_weekly_stock_id'), table_name='labels_weekly')
    op.drop_table('labels_weekly')
    op.drop_index(op.f('ix_kill_switch_events_trigger_type'), table_name='kill_switch_events')
    op.drop_index(op.f('ix_kill_switch_events_strategy_id'), table_name='kill_switch_events')
    op.drop_index(op.f('ix_kill_switch_events_status'), table_name='kill_switch_events')
    op.drop_table('kill_switch_events')
    op.drop_table('kill_switch_configs')
    op.drop_index(op.f('ix_job_runs_job_name'), table_name='job_runs')
    op.drop_table('job_runs')
    op.drop_index(op.f('ix_hyperparam_trials_study_name'), table_name='hyperparam_trials')
    op.drop_index(op.f('ix_hyperparam_trials_strategy_id'), table_name='hyperparam_trials')
    op.drop_index(op.f('ix_hyperparam_trials_status'), table_name='hyperparam_trials')
    op.drop_table('hyperparam_trials')
    op.drop_index(op.f('ix_financial_metrics_stock_id'), table_name='financial_metrics')
    op.drop_index(op.f('ix_financial_metrics_fiscal_period_end'), table_name='financial_metrics')
    op.drop_index(op.f('ix_financial_metrics_as_of_date'), table_name='financial_metrics')
    op.drop_table('financial_metrics')
    op.drop_index(op.f('ix_features_weekly_week_ending'), table_name='features_weekly')
    op.drop_index(op.f('ix_features_weekly_stock_id'), table_name='features_weekly')
    op.drop_index(op.f('ix_features_weekly_feature_name'), table_name='features_weekly')
    op.drop_table('features_weekly')
    op.drop_index(op.f('ix_data_quality_scores_week_ending'), table_name='data_quality_scores')
    op.drop_index(op.f('ix_data_quality_scores_stock_id'), table_name='data_quality_scores')
    op.drop_table('data_quality_scores')
    op.drop_index(op.f('ix_corporate_actions_stock_id'), table_name='corporate_actions')
    op.drop_index(op.f('ix_corporate_actions_action_date'), table_name='corporate_actions')
    op.drop_table('corporate_actions')
    op.drop_index(op.f('ix_backtest_trades_backtest_run_id'), table_name='backtest_trades')
    op.drop_table('backtest_trades')
    op.drop_index(op.f('ix_backtest_runs_strategy_id'), table_name='backtest_runs')
    op.drop_table('backtest_runs')
    op.drop_index(op.f('ix_backtest_metrics_backtest_run_id'), table_name='backtest_metrics')
    op.drop_table('backtest_metrics')
    op.drop_index(op.f('ix_ablation_results_strategy_id'), table_name='ablation_results')
    op.drop_index(op.f('ix_ablation_results_base_strategy_id'), table_name='ablation_results')
    op.drop_table('ablation_results')
    # ### end Alembic commands ###
